version: '3.8'

services:
  app:
    build: .
    container_name: finance-report-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - data-volume:/app/data
    environment:
      - ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/finance_report
      - CHROMA_PERSIST_DIR=/app/data/chroma_db
      - VECTOR_DB_PERSIST_DIR=/app/data/chroma_db
      - STORAGE_UPLOAD_DIR=/app/data/uploads
      - DOCUMENT_PROCESSING_CHUNK_SIZE=1000
      - DOCUMENT_PROCESSING_CHUNK_OVERLAP=200
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/documents/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:15
    container_name: finance-report-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finance_report
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    name: finance-report-postgres-data
  data-volume:
    name: finance-report-data